name: cyseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - bcftools=1.22
  - bedtools=2.31.1
  - biopython=1.86
  - bokeh=3.7.3
  - bwa=0.7.19
  - click=8.3.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - jinja2=3.1.6
  - jq=1.6
  - joblib=1.5.2
  - loguru=0.7.3
  - mappy=2.30
  - minimap2=2.30
  - numpy=2.3.4
  - pandas=2.3.3
  - perbase=1.1.0
  - plotly=6.3.1
  - pyarrow=22.0.0
  - pyfastx=2.2.0
  - pysam=0.23.3
  - python=3.12.4
  - requests=2.28.1
  - samtools=1.22.1
  - scikit-learn=1.7.1
  - seqkit=2.10.1
  - seqtk=1.5
  - tqdm=4.67.1